server:
  port: 8080
spring:
  application:
    name: inventory-management
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/inventory
    password: '1234'
  jpa:
    hibernate:
      ddl-auto: update

